name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t myapp .
      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update deployment.yaml with Docker username
        run: sed -i 's/DOCKER_USERNAME/${{ secrets.DOCKER_USERNAME }}/g' deployment.yaml
      # - name: Deploy to Kubernetes (Minikube)
      #   run: minikube kubectl -- apply -f deployment.yaml
      - name: Set up Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          ./kind create cluster
      - name: Deploy to Kind
        run: kubectl apply -f deployment.yaml
      - name: Verify deployment
        run: |
          kubectl wait --for=condition=ready pod -l app=myapp --timeout=60s
          kubectl port-forward svc/myapp-service 3000:3000 &
          sleep 5
          curl -f http://localhost:3000 || exit 1
